openapi: 3.0.0
info:
  title: DVAPI Test
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /api/profile/upload:
    post:
      tags:
        - default
      summary: Upload
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      parameters:
        - name: Cookie
          in: header
          schema:
            type: string
          example: >-
            auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDIzZTQ0YzI3NmFjMTJjMTQwZGFkM2IiLCJ1c2VybmFtZSI6ImFhIiwiaWF0IjoxNjgwMDczODA3fQ.SYgViC9FtYy_1j-HEVfr87UMv7ojsVVQAIBl5Im1Xh8
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/profile:
    get:
      tags:
        - default
      summary: Profile
      parameters:
        - name: Cookie
          in: header
          schema:
            type: string
          example: >-
            auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDIzZTQ0YzI3NmFjMTJjMTQwZGFkM2IiLCJ1c2VybmFtZSI6ImFhIiwiaWF0IjoxNjgwMDczODA3fQ.SYgViC9FtYy_1j-HEVfr87UMv7ojsVVQAIBl5Im1Xh8
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}